# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Full-Best.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
import resources_rc




class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 504)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QFrame{background: rgb(0, 8, 30);\n"
                                 "border-radius:30px;}\n"
                                 "\n"
                                 "/* VERTICAL SCROLLBAR */\n"
                                 " QScrollBar:vertical {\n"
                                 "    border: none;  \n"
                                 "    background-color: rgb(209, 209, 209);\n"
                                 "    width: 14px;\n"
                                 "    margin: 15px 0 15px 0;\n"
                                 "    border-radius: 0px;\n"
                                 " }\n"
                                 "\n"
                                 "/*  HANDLE BAR VERTICAL */\n"
                                 "QScrollBar::handle:vertical {    \n"
                                 "    background-color: rgb(119, 118, 123);\n"
                                 "    min-height: 30px;\n"
                                 "    border-radius: 7px;\n"
                                 "}\n"
                                 "QScrollBar::handle:vertical:hover{    \n"
                                 "     \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "QScrollBar::handle:vertical:pressed {    \n"
                                 "     \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "\n"
                                 "/* BTN TOP - SCROLLBAR */\n"
                                 "QScrollBar::sub-line:vertical {\n"
                                 "    border: none;\n"
                                 "    background-color: rgb(119, 118, 123);    \n"
                                 "    height: 15px;\n"
                                 "    border-top-left-radius: 7px;\n"
                                 "    border-top-right-radius: 7px;\n"
                                 "    subcontrol-position: top;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "}\n"
                                 "QScrollBar::sub-line:vertical:hover {    \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "QScrollBar::sub-line:vertical:pressed {    \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "\n"
                                 "/* BTN BOTTOM - SCROLLBAR */\n"
                                 "QScrollBar::add-line:vertical {\n"
                                 "    border: none;\n"
                                 "    background-color: rgb(119, 118, 123);\n"
                                 "    height: 15px;\n"
                                 "    border-bottom-left-radius: 7px;\n"
                                 "    border-bottom-right-radius: 7px;\n"
                                 "    subcontrol-position: bottom;\n"
                                 "    subcontrol-origin: margin;\n"
                                 "}\n"
                                 "QScrollBar::add-line:vertical:hover {    \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "QScrollBar::add-line:vertical:pressed {    \n"
                                 "    background-color: rgb(100, 100, 100);\n"
                                 "}\n"
                                 "\n"
                                 "/* RESET ARROW */\n"
                                 "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                 "    background: none;\n"
                                 "}\n"
                                 "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                 "    background: none;\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(1, 3, 5, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimize_3 = QtWidgets.QPushButton(self.frame)
        self.btn_minimize_3.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize_3.setStyleSheet("QPushButton {\n"
                                          "    border: none;\n"
                                          "    border-radius: 8px;        \n"
                                          "    background-color: rgb(255, 170, 0);\n"
                                          "}\n"
                                          "QPushButton:hover {    \n"
                                          "    background-color: rgba(255, 170, 0, 150);\n"
                                          "}")
        self.btn_minimize_3.setText("")
        self.btn_minimize_3.setObjectName("btn_minimize_3")
        self.horizontalLayout.addWidget(self.btn_minimize_3)
        self.btn_close_3 = QtWidgets.QPushButton(self.frame)
        self.btn_close_3.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close_3.setStyleSheet("QPushButton {\n"
                                       "    border: none;\n"
                                       "    border-radius: 8px;        \n"
                                       "    background-color: rgb(255, 0, 0);\n"
                                       "}\n"
                                       "QPushButton:hover {        \n"
                                       "    background-color: rgba(255, 0, 0, 150);\n"
                                       "}")
        self.btn_close_3.setText("")
        self.btn_close_3.setObjectName("btn_close_3")
        self.horizontalLayout.addWidget(self.btn_close_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resources/icons/Covid-anim.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(59, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("background: rgba(255, 255, 255, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 37))
        self.comboBox.setMaximumSize(QtCore.QSize(261, 235))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background: rgb(255, 255, 127);\n"
                                    "color: rgb(45, 45, 45);\n"
                                    "\n"
                                    "")
        self.comboBox.setEditable(False)
        self.comboBox.setMinimumContentsLength(0)
        self.comboBox.setPlaceholderText("")
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 72))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 206))
        self.frame_4.setStyleSheet("background: rgba(255, 255, 255, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 61))
        self.pushButton.setMaximumSize(QtCore.QSize(66, 67))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: rgb(28, 113, 216);\n"
                                      "color: rgb(255, 254, 129);\n"
                                      "border-radius:30px;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(215, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(220, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_minimize_3.setToolTip(_translate("Form", "Minimize"))
        self.btn_close_3.setToolTip(_translate("Form", "Close"))
        self.comboBox.setCurrentText(_translate("Form", "Select Module"))
        self.pushButton.setText(_translate("Form", "GO"))
        self.comboBox.setItemText(0, _translate("Form", "Covid Statistics"))
        self.comboBox.setItemText(1, _translate("Form", "Vaccination centres in Pune"))
        self.comboBox.setItemText(2, _translate("Form", "Symptoms Tracker"))
        self.comboBox.setItemText(3, _translate("Form", "Hospital Management System"))
        self.comboBox.setItemText(4, _translate("Form", "COWIN Vaccines Tracker"))
        self.comboBox.setItemText(5, _translate("Form", "WHO Guidelines"))
        self.comboBox.setItemText(6, _translate("Form", "Fact-Checker"))
        self.comboBox.setItemText(7, _translate("Form", "Treatment info"))
        self.comboBox.setItemText(8, _translate("Form", "Vaccines Info"))
        self.comboBox.setItemText(9, _translate("Form", "Linked Diseases"))
        self.comboBox.setItemText(10, _translate("Form", "Health Guidelines"))
        self.comboBox.setItemText(11, _translate("Form", "Best Practices"))
        self.comboBox.setItemText(12, _translate("Form", "COVID-19 Mutations"))
        self.comboBox.setItemText(13, _translate("Form", "Visual Map of COVID Spread"))
        self.pushButton.clicked.connect(self.fun)




    def fun(self):
        if self.comboBox.currentIndex() == 0:
            subprocess.Popen(['python', 'covid_cases.py'])
        if self.comboBox.currentIndex() == 1:
            subprocess.Popen(['python', 'Vaccination_Centres.py'])
        if self.comboBox.currentIndex() == 2:
            subprocess.Popen(['python', 'Symptoms.py'])
        if self.comboBox.currentIndex() == 3:
            subprocess.Popen(['python', 'username.py'])
        if self.comboBox.currentIndex() == 4:
            subprocess.Popen(['python', 'cowin.py'])
        if self.comboBox.currentIndex() == 5:
            subprocess.Popen(['python', 'who.py'])
        if self.comboBox.currentIndex() == 6:
            subprocess.Popen(['python', 'Fact_Checker.py'])
        if self.comboBox.currentIndex() == 7:
            subprocess.Popen(['python', 'Treatment-info.py'])
        if self.comboBox.currentIndex() == 8:
            subprocess.Popen(['python', 'Vaccines.py'])
        if self.comboBox.currentIndex() == 9:
            subprocess.Popen(['python', 'Related_Diseases.py'])
        if self.comboBox.currentIndex() == 10:
            subprocess.Popen(['python', 'Health_Guidelines.py'])
        if self.comboBox.currentIndex() == 11:
            subprocess.Popen(['python', 'Best_Practices.py'])
        if self.comboBox.currentIndex() == 12:
            subprocess.Popen(['python', 'Covid_Mutations.py'])
        if self.comboBox.currentIndex() == 13:
            subprocess.Popen(['python', 'Covid_Map.py'])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

