# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Symptoms_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import resources_rc


class Ui_Form(object):


    def submit(self):
        A = self.lineEdit.text()
        B = self.lineEdit_2.text()
        C = self.lineEdit_3.text()
        D = self.lineEdit_4.text()
        E = self.lineEdit_5.text()

        if A>='18' and A<='44' and B == 'Yes' and C == 'No' and D == 'No' and E == 'No':
                msg = QMessageBox()
                msg.setWindowTitle('Safe')
                msg.setText('You are safe')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A>='18' and A<='44' and B == 'No' and C == 'Yes' or D == 'Yes' or E == 'Yes':
                msg = QMessageBox()
                msg.setWindowTitle('Risk')
                msg.setText('You are at a risk of catching COVID-19 with mild to severe symptoms')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '0' and A <= '17' and B == 'Yes' and C == 'No' and D == 'No' and E == 'No':
                msg = QMessageBox()
                msg.setWindowTitle('Safe')
                msg.setText('You are safe, with little risk')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '0' and A <= '17' and B == 'No' and C == 'Yes' or D == 'Yes' or E == 'Yes':
                msg = QMessageBox()
                msg.setWindowTitle('Risk')
                msg.setText('You are at a risk of catching COVID-19 with severe symptoms')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '45' and A <= '64' and B == 'Yes' and C == 'No' and D == 'No' and E == 'No':
                msg = QMessageBox()
                msg.setWindowTitle('Safe')
                msg.setText('You are safe')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '45' and A <= '64' and B == 'No' and C == 'Yes' or D == 'Yes' or E == 'Yes':
                msg = QMessageBox()
                msg.setWindowTitle('Risk')
                msg.setText('You are at a risk of catching COVID-19 with severe symptoms or hospitalisation')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '65' and A <= '74' and B == 'Yes' and C == 'No' and D == 'No' and E == 'No':
                msg = QMessageBox()
                msg.setWindowTitle('Safe')
                msg.setText('You are safe, but may experience mild symptoms')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '65' and A <= '74' and B == 'No' and C == 'Yes' or D == 'Yes' or E == 'Yes':
                msg = QMessageBox()
                msg.setWindowTitle('Risk')
                msg.setText('You are at a risk of catching COVID-19 with tentative hospitalisation')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '75' and A <= '150' and B == 'Yes' and C == 'No' and D == 'No' and E == 'No':
                msg = QMessageBox()
                msg.setWindowTitle('Safe')
                msg.setText('You may experience mild or severe symptoms as per your immunity')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '75' and A <= '150' and B == 'No' and C == 'Yes' or D == 'Yes' or E == 'Yes':
                msg = QMessageBox()
                msg.setWindowTitle('Risk')
                msg.setText('You are at a risk of severe fatality or mortality')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        elif A >= '0' and A <= '150' and B == 'No' and C == 'No' or D == 'No' or E == 'No':
                msg = QMessageBox()
                msg.setWindowTitle('Safe')
                msg.setText('You are safe, but are advised to get vaccinated')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()

        else:
                msg = QMessageBox()

                msg.setWindowTitle('Error')
                msg.setText('Please put correct values')
                msg.setStyleSheet('background-color:darkslategray; color:White')

                x = msg.exec()




    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(646, 469)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("QFrame{ \n"
"    background-image: url(:/resources/icons/w10.jpg) no-repeat center center fixed;\n"
"border: 2px;\n"
"border-radius:30px;\n"
"}\n"
"\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none; \n"
"    background-color: rgb(61, 56, 70);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(190, 190, 190);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(200, 200, 200);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(200, 200, 200);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL SCROLLBAR */\n"
" QScrollBar:horizontal {\n"
"    border: none; \n"
"    background-color: rgb(61, 56, 70);\n"
"    height: 14px;\n"
"    margin: 0px 15px 0px 15px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR HORIZONTAL */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(190, 190, 190);\n"
"    min-width: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(200, 200, 200);\n"
"    width: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal{\n"
"    border: none;\n"
"    background-color: rgb(200, 200, 200);\n"
"    width: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(238, 255, 145);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(8, 11, 12, 8)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setVerticalSpacing(11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(20, 215))
        self.scrollArea.setMaximumSize(QtCore.QSize(900, 5003))
        self.scrollArea.setStyleSheet("background: rgba(191, 64, 64, 0);")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -180, 600, 1200))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(20, 1200))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(900, 5008))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(1, 3, 5, -1)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimize_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_minimize_3.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize_3.setText("")
        self.btn_minimize_3.setObjectName("btn_minimize_3")
        self.horizontalLayout.addWidget(self.btn_minimize_3)
        self.btn_close_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_close_3.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close_3.setText("")
        self.btn_close_3.setObjectName("btn_close_3")
        self.horizontalLayout.addWidget(self.btn_close_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setEnabled(True)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_4.setMaximumSize(QtCore.QSize(600, 400))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 8)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(10, 62))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(105, 9, 9);\n"
"AlignCenter;\n"
"border:2px;\n"
"border-radius:30px;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setMinimumSize(QtCore.QSize(20, 60))
        self.label_3.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"AlignCenter;\n"
"border:0px;\n"
"border-radius:30px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setStyleSheet("background: rgba(191, 64, 64, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setEnabled(True)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_8.setMaximumSize(QtCore.QSize(600, 400))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 8)
        self.gridLayout_9.setHorizontalSpacing(10)
        self.gridLayout_9.setVerticalSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(10, 62))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(271, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(105, 9, 9);\n"
"AlignCenter;\n"
"border:2px;\n"
"border-radius:30px;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_9.addWidget(self.lineEdit_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMinimumSize(QtCore.QSize(19, 60))
        self.label_4.setMaximumSize(QtCore.QSize(277, 200))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"AlignCenter;\n"
"border:0px;\n"
"border-radius:30px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_8, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(70, 60))
        self.label_2.setMaximumSize(QtCore.QSize(650, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"border:0px;\n"
"border-radius:30px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(90, 90))
        self.listWidget.setMaximumSize(QtCore.QSize(800, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"border:0px;\n"
"border-radius:30px;")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_3.addWidget(self.listWidget, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(10, 62))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(535, 200))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(105, 9, 9);\n"
"AlignCenter;\n"
"border:2px;\n"
"border-radius:30px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 3, 1, 1, 2)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setMinimumSize(QtCore.QSize(66, 60))
        self.label_5.setMaximumSize(QtCore.QSize(608, 200))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMinimumSize(QtCore.QSize(16, 15))
        self.listWidget_2.setMaximumSize(QtCore.QSize(500, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_2.setFont(font)
        self.listWidget_2.setStyleSheet("background: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"border:2px;\n"
"border-radius:30px;")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.gridLayout_5.addWidget(self.listWidget_2, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(10, 62))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(490, 199))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(105, 9, 9);\n"
"AlignCenter;\n"
"border:2px;\n"
"border-radius:30px;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_5.addWidget(self.lineEdit_4, 2, 1, 1, 2)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setMinimumSize(QtCore.QSize(40, 60))
        self.label_6.setMaximumSize(QtCore.QSize(600, 500))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(10, 62))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(535, 199))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(105, 9, 9);\n"
"AlignCenter;\n"
"border:2px;\n"
"border-radius:30px;")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_6.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(9, 60))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 200))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: rgb(61, 56, 70);\n"
"color: rgb(255, 254, 129);\n"
"border:2px;\n"
"border-radius:30px;")
        self.pushButton.setIconSize(QtCore.QSize(22, 11))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.pushButton.clicked.connect(self.submit)
        self.lineEdit.setValidator(QtGui.QIntValidator())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_minimize_3.setToolTip(_translate("Form", "Minimize"))
        self.btn_close_3.setToolTip(_translate("Form", "Close"))
        self.label_3.setText(_translate("Form", "  Enter Your Age   "))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Yes/No"))
        self.label_4.setText(_translate("Form", " Have you taken vaccine?    "))
        self.label_2.setText(_translate("Form", " Are you currently experiencing any of the following symptoms       "))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "Cough"))
        item = self.listWidget.item(1)
        item.setText(_translate("Form", "Fever"))
        item = self.listWidget.item(2)
        item.setText(_translate("Form", "Sore Throat"))
        item = self.listWidget.item(3)
        item.setText(_translate("Form", "Chest congestion or runny nose"))
        item = self.listWidget.item(4)
        item.setText(_translate("Form", "Body ache"))
        item = self.listWidget.item(5)
        item.setText(_translate("Form", "Difficult in Breathing"))
        item = self.listWidget.item(6)
        item.setText(_translate("Form", "Pink Eyes"))
        item = self.listWidget.item(7)
        item.setText(_translate("Form", "Loss of senses of small and taste"))
        item = self.listWidget.item(8)
        item.setText(_translate("Form", "Hearing impairment"))
        item = self.listWidget.item(9)
        item.setText(_translate("Form", "Gastrointestinal Symptoms"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Yes/No"))
        self.label_5.setText(_translate("Form", " Do you have any of the following pre-existing conditions?   "))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("Form", "Diabetes"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("Form", "Hypertension"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("Form", "Lung disease"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("Form", "Heart disease"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("Form", "Kidney Disorder"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("Form", "Asthma"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Yes/No"))
        self.label_6.setText(_translate("Form", " Have you visited any COVID-19 affected areas in last 14 days?  "))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Yes/No"))
        self.pushButton.setText(_translate("Form", "SUBMIT"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
