# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Akshita.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(847, 514)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setItalic(True)
        Form.setFont(font)
        Form.setStyleSheet("QWidget { border: 0; \n"
"\n"
"background-color: rgb(49, 122, 210);}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Nimbus Sans Narrow [urw]")
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(2, 119, 189);\n"
"border:2px;\n"
"border-radius:30px;}\n"
"\n"
"QFrame::pane{\n"
"border:0;}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;  \n"
"    background-color: rgb(209, 209, 209);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(119, 118, 123);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"     \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"     \n"
"    background-color:rgb(255, 255, 127);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(119, 118, 123);    \n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color:rgb(255, 255, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color:rgb(255, 255, 127);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(119, 118, 123);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color:rgb(255, 255, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* HORIZONTAL SCROLLBAR */\n"
" QScrollBar:horizontal {\n"
"    border: none; \n"
"    background-color: rgb(209, 209, 209);\n"
"    height: 14px;\n"
"    margin: 0px 15px 0px 15px;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR HORIZONTAL */\n"
"QScrollBar::handle:horizontal {    \n"
"    background-color: rgb(119, 118, 123);\n"
"    min-width: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QScrollBar::handle:horizontal:pressed {    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color: rgb(119, 118, 123);    \n"
"    width: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:horizontal{\n"
"    border: none;\n"
"    background-color: rgb(119, 118, 123);\n"
"    width: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {    \n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 148, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(2, 119, 189))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 52, 54, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tableWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(11)
        font.setItalic(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet(" QHeaderView::section {\n"
"                    border-top: 0px solid 4181C0;\n"
"                    border-bottom: 1px solid 4181C0;\n"
"                    border-right: 1px solid 4181C0;                    \n"
"                    \n"
"                    \n"
"                    background-color: rgb(53, 132, 228);\n"
"                    color: rgb(250, 255, 0);}\n"
"\n"
"\n"
"QTableWidget::columns{\n"
"    \n"
"    \n"
"                     background-color: #2F2F2F;\n"
"                    border: 1px solid #4181C0;                 \n"
"                    color: rgb(250, 255, 0);\n"
"                    selection-background-color: #4181C0;\n"
"                    selection-color: rgb(250, 255, 0);\n"
"\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"color:white;\n"
"    \n"
"    background-color: rgb(131, 54, 54);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tableWidget.setLineWidth(8)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 247, 14))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 6, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(119)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(24)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(70)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.frame_btns = QtWidgets.QFrame(self.frame_2)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_5.setContentsMargins(5, 1, 3, 4)
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize_3 = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize_3.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize_3.setText("")
        self.btn_minimize_3.setObjectName("btn_minimize_3")
        self.horizontalLayout_5.addWidget(self.btn_minimize_3)
        self.btn_close_3 = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close_3.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close_3.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close_3.setText("")
        self.btn_close_3.setObjectName("btn_close_3")
        self.horizontalLayout_5.addWidget(self.btn_close_3)
        self.gridLayout.addWidget(self.frame_btns, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Number of doses"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Approved age group"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Effectiveness against death"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Effective against current variants"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Efficacy against disease"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "Emergency use authorization ( U.S.A)"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "Emergency use authorization (India)"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "Type of vaccine"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Common Side-Effects"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "Testing for Children? (in U.S.A)"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "Price (USD)"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "Who should not get the vaccine?"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Pfizer"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Moderna"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Janssen"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "AstraZeneca"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Novavax"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Sputnik V"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Covaxin"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "2, 21 days apart"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Form", "2, 28 days apart"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Form", "2, 4-12 weeks apart"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Form", "2, 21 days apart"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("Form", "2, 21 days apart"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("Form", "2, 28 days apart"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Form", "12 years+"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Form", "18 years and older"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Form", "18 years and older"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Form", "18 years and older"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Form", "18 years and older"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("Form", "18 years and older"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("Form", "12 years and above"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("Form", "Yes"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Form", "95% (86% in 65 years and older)"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Form", "94.1% (86% in 65 years and older)"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Form", "72% (86% against severe disease)"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Form", "70% (100% for severe disease)"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Form", "95.6% (UK trials)"))
        item = self.tableWidget.item(4, 5)
        item.setText(_translate("Form", "91.4% (Original Strains)"))
        item = self.tableWidget.item(4, 6)
        item.setText(_translate("Form", "78% efficacy against mild, moderate and severe disease"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Form", "Approved"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Form", "Approved"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Form", "Approved"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Form", "Not Approved in U.S."))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(5, 5)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(5, 6)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Form", "Approved (as Covishield)"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Form", "Not Approved"))
        item = self.tableWidget.item(6, 5)
        item.setText(_translate("Form", "Approved"))
        item = self.tableWidget.item(6, 6)
        item.setText(_translate("Form", "Approved"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Form", "mRNA"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Form", "mRNA"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Form", "Vector (modified common cold virus)"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("Form", "Inactivated common cold virus"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("Form", "Recombinant protein/adjuvants"))
        item = self.tableWidget.item(7, 5)
        item.setText(_translate("Form", "Adenovirus based"))
        item = self.tableWidget.item(7, 6)
        item.setText(_translate("Form", "Inactivated SARS-CoV-2 virus using Whole-Virion Inactivated Vero-Cell platform technology"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Form", "Fatigue,\n"
"headache,\n"
"chills,\n"
"muscle\n"
"pain"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Form", "Fatigue,\n"
"headache,\n"
"chills,\n"
"muscle\n"
"pain"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Form", "Fatigue,\n"
"headache,\n"
"chills,\n"
"muscle\n"
"pain"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("Form", "Fatigue,\n"
"headache,\n"
"chills, muscle\n"
"pain"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Form", "Fatigue,\n"
"headache,\n"
"chills,\n"
"muscle pain"))
        item = self.tableWidget.item(8, 5)
        item.setText(_translate("Form", "Injection site\n"
"pain, headache,\n"
"fatigue, Flu-like\n"
"illness"))
        item = self.tableWidget.item(8, 6)
        item.setText(_translate("Form", "Injection site pain,\n"
"headache, fatigue,\n"
"fever, body ache,\n"
"abdominal pain,\n"
"nausea and\n"
"vomiting,\n"
"dizziness-\n"
"giddiness, tremor,\n"
"sweating, cold,\n"
"cough and\n"
"injection site\n"
"swelling."))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Form", "Yes, ages\n"
"12-15"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Form", "Yes, ages\n"
"12-17"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Form", "TBD"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("Form", "TBD"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Form", "TBD"))
        item = self.tableWidget.item(9, 5)
        item.setText(_translate("Form", "TBD"))
        item = self.tableWidget.item(9, 6)
        item.setText(_translate("Form", "Yes, ages\n"
"12-17"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Form", "$23/dose"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Form", "$25-$37"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Form", "$10"))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("Form", "$3-$4"))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("Form", "$16"))
        item = self.tableWidget.item(10, 5)
        item.setText(_translate("Form", "$10"))
        item = self.tableWidget.item(10, 6)
        item.setText(_translate("Form", "$2"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Form", "History of\n"
"allergic\n"
"reaction\n"
"to\n"
"polyethyle\n"
"ne glycol"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Form", "History of\n"
"allergic\n"
"reaction\n"
"to\n"
"polyethyle\n"
"ne glycol"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Form", "History of\n"
"severe\n"
"reaction to\n"
"vaccine\n"
"ingredients,\n"
"risk of rare"))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("Form", "TBD"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("Form", "TBD"))
        item = self.tableWidget.item(11, 5)
        item.setText(_translate("Form", "History of\n"
"allergic\n"
"reaction\n"
"anaphylaxis,\n"
"age below 18\n"
"years."))
        item = self.tableWidget.item(11, 6)
        item.setText(_translate("Form", "Pregnant and\n"
"breastfeeding\n"
"women, Person\n"
"having allergies,\n"
"fever or bleeding\n"
"disorder, weaker"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.btn_minimize_3.setToolTip(_translate("Form", "Minimize"))
        self.btn_close_3.setToolTip(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
